# Generated by Django 6.0.3 on 2026-04-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profiles/default_user.png', null=True, upload_to='profiles/%Y/%m/'),
        ),
    ]
