# Generated by Django 6.0.3 on 2026-04-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
